### ISSUE TITLE
Outdated Wiki link

### ISSUE THREAD

**Issue by TheSweatyYeti** [MarshDeer/howlongmojang#16]
In the Damage Tilt bug info, the text "Update 1.3.1" takes you to the old [Fandom Minecraft wiki](https://minecraft.fandom.com/wiki/Minecraft_Wiki) for [Java Edition 1.3.1](https://minecraft.fandom.com/wiki/Java_Edition_1.3.1#General_2).

Now that the wiki has moved away from Fandom, this should be updated to take you to the new [Minecraft wiki](https://minecraft.wiki/) for [Java Edition 1.3.1](https://minecraft.wiki/w/Java_Edition_1.3.1#General_2).

**Comment by MarshDeer** [comment]
Closed by commit 02680a2
