### ISSUE TITLE
combat update V2 (aka "combat test")

### ISSUE THREAD

**Issue by wasakoki** [MarshDeer/howlongmojang#3]
first mentioned here: https://www.reddit.com/r/Minecraft/comments/c5mqwv/a_custom_java_edition_snapshot_to_test_new_combat/

wiki page with most relevant information about it: https://minecraft.fandom.com/wiki/Java_Edition_Combat_Tests

even though it wasn't quite an announced feature like everything else on your list, it's definitely something that confirmed they were working on a new combat system, and the playable snapshots did nothing but tease the updates to minecraft's player base (much like how everything else on your list was teased by mojang). fast forward and here we are with no update since the last snapshot ~2 years ago.

**Comment by MarshDeer** [comment]
100% adding this one later

**Comment by MarshDeer** [comment]
Added in [commit cb5d244](https://github.com/MarshDeer/howlongmojang/commit/cb5d244)
