### ISSUE TITLE
Fireflies 😔 

### ISSUE THREAD

**Issue by psychonemesis** [MarshDeer/howlongmojang#5]
**Feature Request**
_(Feel free to not really follow this template if your suggestion doesn't fit it!)_

* **This feature should be added to the list!**
 - Fireflies

* **I think it should be added because...**
 - It would add some much needed ambiance to the overworld's lackluster default swamps, which currently lack any unique attributes apart from Frogs spawning and Blue Orchids, as well as adding a similar ambiance to mangrove swamps, or to other biomes if they can be transported.

* **Mojang promised/last spoke of it/updated on it here**
 - https://www.youtube.com/watch?v=or1DfXdqu3U

* **It should have this as an icon**
 - https://static.wikia.nocookie.net/minecraft_gamepedia/images/f/fc/Firefly.gif/revision/latest/scale-to-width-down/300?cb=20211030110807

* **And this as a background**
 - https://cdna.artstation.com/p/assets/images/images/042/400/684/large/mariana-salimena-swamp-artstation.jpg?1634406914

* **Any additional comments?**
 - It should also be noted that though Swamps were included in a prior biome vote and are technically being updated, many members of the community were under the impression that default swamps would undergo some sort of physical change, such as the spawning of occasional mangrove trees. Right now, default swamps have no physical attributes that makes them any different from how they were before.

_(Thank you for your contribution!)_

**Comment by MarshDeer** [comment]
Can't believe I had forgotten to add the one feature removal that got me coding this lmao

Will add!

**Comment by MarshDeer** [comment]
Closed by commit [9fa5534](https://github.com/MarshDeer/howlongmojang/commit/9fa5534ba76aa5911a63989fa87cd0bf65b8c6ee)
