### ISSUE TITLE
Small grammar issue

### ISSUE THREAD

**Issue by MacchuPicchu3** [MarshDeer/howlongmojang#7]
Hey, just a small thing. The usage of the words "in" and "on" for dates is backwards on this site.

"On" is for specific dates, as in "on November 17, 2021 . . . "
"In" is for less specific dates, like whole months or years, as in "in October 2020"

The first mistake happens in almost every card, while the second mistake only happens in the damage tilt bug card.

I really like this site by the way– I hope I'm not coming across as rude or condescending here. I honestly had forgotten how long ago some of these features had been promised. Thank you :D

**Comment by MarshDeer** [comment]
I literally have an English-adjacent degree and I keep getting these prepositions mixed up lmao

Thank you for the heads-up! Will fix in a couple hours~

**Comment by MarshDeer** [comment]
Fixed in commit [2bf44b7](https://github.com/MarshDeer/howlongmojang/commit/2bf44b7e9e52b353d1a171255f3dfe8295d7c9e4)
